name: Feature request
description: Propose new features
body:
- type: checkboxes
  attributes:
    label: Prerequisites
    options:
    - label: I have read the documentation and the proposed feature is not implemented.
      required: true
- type: textarea
  attributes:
    label: Description
    description: >
      A description of the feature proposal. State when this feature can be
      useful. If applicable, add screenshots or drawing to better illustrate the
      proposal.
  validations:
    required: true
